spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lock
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      operationsSorter: method
      tagsSorter: alpha
      display-request-duration: true

  data:
    redis:
      host: localhost
      port: 6379

#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: 00000f8b97d04bc4ecfade9e27170088    # REST API KEY
#            redirect-uri: http://localhost:8080/api/auth/login/kakao
##            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#            client-secret: ""
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            scope:
#              - profile_nickname
#              - profile_image
#              - account_email
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id


jwt_secret: S+41vjbYmuJi9mCcfw0NxyoeAeKqZCMxadSSMWA+XmT7DZ3Mam+EARXnryqn6gFYwus+VW1yqbl9/gz3lsMg6Q==

jwt:
  access-token-validity: 3600000       # 1시간 (ms 단위)
  refresh-token-validity: 1209600000   # 14일 (ms 단위)

app:
  env: local
  local: true

oauth:
  kakao:
    client-id: 00000f8b97d04bc4ecfade9e27170088    # REST API KEY
    local: http://localhost:8080/api/auth/login/kakao
#      local: http://localhost:3000/login/kakao
    prod: http://localhost:8080    # 프론트 배포 url
  google:
    client-id: 20011764155-e0sgfl3l661pbp1tc693jiiji1s6r3ut.apps.googleusercontent.com
    client-secret: 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
    local: http://localhost:8080/api/auth/login/google
    prod:
